cmake_minimum_required(VERSION 4.2)
project(leetcode_yandex_preparation)

set(CMAKE_CXX_STANDARD 20)

add_executable(leetcode_yandex_preparation main.cpp
        easy/two-sum/TwoSum.cpp
        easy/two-sum/TwoSum.h
        easy/best-time-to-buy-and-sell/BestTimeToBuyAndSell.cpp
        easy/best-time-to-buy-and-sell/BestTimeToBuyAndSell.h
        easy/contains-duplicate/ContainsDuplicate.cpp
        easy/contains-duplicate/ContainsDuplicate.h
        medium/maximum-subarray/MaximumSubarray.cpp
        medium/maximum-subarray/MaximumSubarray.h
        easy/move-zeroes/MoveZeroes.cpp
        easy/move-zeroes/MoveZeroes.h
        easy/majority-element/MajorityElement.cpp
        easy/majority-element/MajorityElement.h
        medium/product-except-self/ProductExceptSelf.cpp
        medium/product-except-self/ProductExceptSelf.h
        medium/merge-intervals/MergeIntervals.cpp
        medium/merge-intervals/MergeIntervals.h
        medium/insert-interval/InsertInterval.cpp
        medium/insert-interval/InsertInterval.h
        medium/non-overlapping-intervals/NonOverlappingIntervals.cpp
        medium/non-overlapping-intervals/NonOverlappingIntervals.h
        hard/first-missing-positive/FirstMissingPositive.cpp
        hard/first-missing-positive/FirstMissingPositive.h
        hard/trapping-rain-water/TrappingRainWater.cpp
        hard/trapping-rain-water/TrappingRainWater.h
        medium/range-sum-query-2d/NumMatrix.cpp
        medium/range-sum-query-2d/NumMatrix.h
        medium/rotate-array/RotateArray.cpp
        medium/rotate-array/RotateArray.h
        medium/jump-game/JumpGame.cpp
        medium/jump-game/JumpGame.h
        medium/jump-game/subarray-sum-equals-k/SubarraySumEqualsK.cpp
        medium/jump-game/subarray-sum-equals-k/SubarraySumEqualsK.h
        medium/search-2d-matrix/SearchMatrix.cpp
        medium/search-2d-matrix/SearchMatrix.h
        easy/sqrt/Sqrt.cpp
        easy/sqrt/Sqrt.h
        easy/maximum-69-number/Maximum69Number.cpp
        easy/maximum-69-number/Maximum69Number.h
        easy/reverse-linked-list/ReverseLinkedList.cpp
        easy/reverse-linked-list/ReverseLinkedList.h
        medium/valid-sudoku/ValidSudoku.cpp
        medium/valid-sudoku/ValidSudoku.h
        easy/valid-palindrome/ValidPalindrome.cpp
        easy/valid-palindrome/ValidPalindrome.h
        easy/summary-ranges/SummaryRanges.cpp
        easy/summary-ranges/SummaryRanges.h
        medium/my-atoi/MyAtoi.cpp
        medium/my-atoi/MyAtoi.h
        medium/compare-version-numbers/CompareVersionNumbers.cpp
        medium/compare-version-numbers/CompareVersionNumbers.h
        medium/zigzag-conversion/ZigzagConversion.cpp
        medium/zigzag-conversion/ZigzagConversion.h
        hard/substring-of-concatenation-of-all-words/SubstringOfConcatenationOfAllWords.cpp
        hard/substring-of-concatenation-of-all-words/SubstringOfConcatenationOfAllWords.h
        medium/decode-ways/DecodeWays.cpp
        medium/decode-ways/DecodeWays.h
        easy/merge-sorted-arrays/MergeSortedArrays.cpp
        easy/merge-sorted-arrays/MergeSortedArrays.h
        hard/minimum-window-substring/MinimumWindowSubstring.cpp
        hard/minimum-window-substring/MinimumWindowSubstring.h
        medium/longest-substring-without-repeating-characters/LongestSubstringWithoutRepeatingCharacters.cpp
        medium/longest-substring-without-repeating-characters/LongestSubstringWithoutRepeatingCharacters.h
        medium/longest-palindrome-substring/LongestPalindromeSubstring.cpp
        medium/longest-palindrome-substring/LongestPalindromeSubstring.h
        easy/ransom-note/RansomNote.cpp
        easy/ransom-note/RansomNote.h
        easy/group-anagrams/GroupAnagrams.cpp
        easy/group-anagrams/GroupAnagrams.h
        medium/rotate-list/RotateList.cpp
        medium/rotate-list/RotateList.h
        medium/reorder-list/ReorderList.cpp
        medium/reorder-list/ReorderList.h
        yandex-interview-session/first-task/FirstTask.cpp
        yandex-interview-session/first-task/FirstTask.h
        yandex-interview-session/second-task/SecondTask.cpp
        yandex-interview-session/second-task/SecondTask.h
        medium/number-of-islands/NumberOfIslands.cpp
        medium/number-of-islands/NumberOfIslands.h
        medium/max-area-of-island/MaxAreaOfIsland.cpp
        medium/max-area-of-island/MaxAreaOfIsland.h
        easy/flood-fill/FloodFill.cpp
        easy/flood-fill/FloodFill.h
        medium/find-peak-element/FindPeakElement.cpp
        medium/find-peak-element/FindPeakElement.h
        medium/time-based-key-value-store/TimeMap.cpp
        medium/time-based-key-value-store/TimeMap.h
        easy/maximum-average-subarray/MaximumAverageSubarray.cpp
        easy/maximum-average-subarray/MaximumAverageSubarray.h
        medium/count-good-nodes-in-binary-tree/CountGoodNodesInBinaryTree.cpp
        medium/count-good-nodes-in-binary-tree/CountGoodNodesInBinaryTree.h
        medium/flatten-binary-tree-to-linked-list/FlattenBinaryTreeToLinkedList.cpp
        medium/flatten-binary-tree-to-linked-list/FlattenBinaryTreeToLinkedList.h
)
